<div 
    class='payment-method-note lmerchant-checkout-note' 
    style='text-align: left; margin-bottom: 1.5rem; font-size: 13px;'>
        <h3 style="font-size: 1.5rem">
        <span style="color: #00a4e4;">
    Pay now with Lmerchant
</div>
<button 
    type="button" 
    data-role="proceed-to-checkout" 
    onclick="window.location.href='https://simulation.enterprisesecure.com.au/hosted/?configId=252920a5-7c30-4f5f-a7cf-a7086ce564f7&userName=jharjadi.latitude.demo&simulation=00&merchReference=BF9C27B6-68AD-11EA-BE0B-EE793190D11B&amount=200.00&verifyMessage=7b7862774c1e0f9849d1854e1b0f67d9e0b1257bf7064d822d47dc9850a0d180'" 
    title="Pay now with Lmerchant" 
    class="action"
    style="background: white">
    <img 
        src="https://dvh1deh6tagwk.cloudfront.net/niche-builder/5d5de04c57373.png" 
        alt="Pay with Lmerchant"
        height="50"
    />
</button>