<!-- Latitude Interest Free Snippet - Start -->
<?php if ($block->showContainer()): ?>
    <div class="payment-method-note" id="latitude-banner-container"></div>
<?php endif; ?>

<script type="text/javascript">  
    window.LatitudeCheckout = <?php echo $block->getOptions(); ?>;
    window.LatitudeCheckoutOverride = <?php echo $block->getOverride(); ?>;

    (function () {
        function asyncLoad() {
            var curr = document.createElement("script");
            curr.type = "text/javascript";
            curr.async = true;
            curr.src = "<?php echo $block->getScriptURL(); ?>";
        
            var scr = document.getElementsByTagName("script")[0];
            scr.parentNode.insertBefore(curr, scr);
        }
        
        if (window.attachEvent) {
            window.attachEvent("onload", asyncLoad);
        } else {
            window.addEventListener("load", asyncLoad, false);
        }
    })();
</script>
<!-- Latitude Interest Free Snippet - End -->