<!-- Latitude Interest Free Snippet - Start -->
<?php
    $latitudeContent = $block->getContent();
    $displayType = $block->getDisplayType();
?>

<?php if ($displayType == "full_width") : ?>
    <div class="payment-method-note latitude-widget-container">
        <?php echo $latitudeContent["title"]; ?>
        <span class="latitude-widget-logo">
            <img style="height:28px" src="<?php echo $latitudeContent["logoURL"]; ?>"/>
        </span>
            
        <span class="latitude-widget-text-container">
            <a target="_blank" href="<?php echo $latitudeContent["applyURL"]; ?>">
                What's this?
            </a>
        </span>
    </div>
<?php endif; ?>

<?php if ($displayType == "inline") : ?>
    <span class="latitude-widget-logo">
        <a target="_blank" href="<?php echo $latitudeContent["applyURL"]; ?>">
            <img style="height:28px" src="<?php echo $latitudeContent["logoURL"]; ?>"/>
        </a>
    </span>
<?php endif; ?>
<!-- Latitude Interest Free Snippet - End -->